apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: guestbook-ui
  name: guestbook-ui-httpproxy
spec:
  routes:
  - conditions:
    - prefix: /
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /
    services:
    - name: guestbook-ui
      port: 80
  virtualhost:
    fqdn: gb-ui.example.local
