apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: guestbook
  name: guestbook-ui-httpproxy
spec:
  tcpproxy:
    services:
    - name: guestbook-ui
      port: 80
  virtualhost:
    fqdn: guest-book.example.local
